name: CollabVM Server

on: [push, pull_request]

jobs:
  ubuntu_x64: # Latest version of Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with: 
          submodules: true
      - name: Install Dependencies
        id: depends
        run: | 
          mkdir build
          sudo apt install -y libvncserver-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libspdlog-dev libfmt-dev cmake ninja-build
      - name: Install latest LLVM/Clang
        id: llvm
        run: |
          # We need the latest version of Clang to build the server.
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      - name: Build
        id: build
        run: |
          # Use clang instead of GCC
          export CC=/usr/bin/clang-13
          export CXX=/usr/bin/clang++-13
          cmake -B build -GNinja -DCMAKE_BUILD_TYPE=Release
          cd build
          cmake --build .
      - name: Upload to GitHub Release
        uses: svenstaro/upload-release-action@2.2.1
        id: uploadfiles
        with: 
          asset_name: collab-vm-server-linux-amd64
          release_name: CollabVM Server 3.0
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/collab-vm-server
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: true
          body: "This is an unstable build of collab-vm-server 3.0 automatically generated by GitHub Actions. It is not usable yet and is not suitable for production."
